/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xueqiya_spiderman_FFmpeg */

#ifndef _Included_com_xueqiya_spiderman_FFmpeg
#define _Included_com_xueqiya_spiderman_FFmpeg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xueqiya_spiderman_FFmpeg
 * Method:    run
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xueqiya_spiderman_FFmpeg_run
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
